/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EKYCRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllProviders"
      | "getProviderCount"
      | "getProviderDetails"
      | "isProviderActive"
      | "owner"
      | "providerAddresses"
      | "providers"
      | "registerProvider"
      | "renounceOwnership"
      | "setProviderStatus"
      | "transferOwnership"
      | "updateProviderMetadata"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProviderMetadataUpdated"
      | "ProviderRegistered"
      | "ProviderStatusChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderDetails",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProviderActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "providerAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "providers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProvider",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setProviderStatus",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProviderMetadata",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProviderActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "providerAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "providers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProviderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProviderMetadata",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderMetadataUpdatedEvent {
  export type InputTuple = [provider: AddressLike, metadataURI: string];
  export type OutputTuple = [provider: string, metadataURI: string];
  export interface OutputObject {
    provider: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderRegisteredEvent {
  export type InputTuple = [provider: AddressLike, name: string];
  export type OutputTuple = [provider: string, name: string];
  export interface OutputObject {
    provider: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderStatusChangedEvent {
  export type InputTuple = [provider: AddressLike, isActive: boolean];
  export type OutputTuple = [provider: string, isActive: boolean];
  export interface OutputObject {
    provider: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EKYCRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EKYCRegistry;
  waitForDeployment(): Promise<this>;

  interface: EKYCRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllProviders: TypedContractMethod<[], [string[]], "view">;

  getProviderCount: TypedContractMethod<[], [bigint], "view">;

  getProviderDetails: TypedContractMethod<
    [provider: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        metadataURI: string;
        isActive: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  isProviderActive: TypedContractMethod<
    [provider: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  providerAddresses: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  providers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        metadataURI: string;
        isActive: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  registerProvider: TypedContractMethod<
    [provider: AddressLike, name: string, metadataURI: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setProviderStatus: TypedContractMethod<
    [provider: AddressLike, isActive: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateProviderMetadata: TypedContractMethod<
    [provider: AddressLike, metadataURI: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllProviders"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProviderCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProviderDetails"
  ): TypedContractMethod<
    [provider: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        metadataURI: string;
        isActive: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isProviderActive"
  ): TypedContractMethod<[provider: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "providerAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "providers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        metadataURI: string;
        isActive: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProvider"
  ): TypedContractMethod<
    [provider: AddressLike, name: string, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProviderStatus"
  ): TypedContractMethod<
    [provider: AddressLike, isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProviderMetadata"
  ): TypedContractMethod<
    [provider: AddressLike, metadataURI: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderMetadataUpdated"
  ): TypedContractEvent<
    ProviderMetadataUpdatedEvent.InputTuple,
    ProviderMetadataUpdatedEvent.OutputTuple,
    ProviderMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProviderRegistered"
  ): TypedContractEvent<
    ProviderRegisteredEvent.InputTuple,
    ProviderRegisteredEvent.OutputTuple,
    ProviderRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderStatusChanged"
  ): TypedContractEvent<
    ProviderStatusChangedEvent.InputTuple,
    ProviderStatusChangedEvent.OutputTuple,
    ProviderStatusChangedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProviderMetadataUpdated(address,string)": TypedContractEvent<
      ProviderMetadataUpdatedEvent.InputTuple,
      ProviderMetadataUpdatedEvent.OutputTuple,
      ProviderMetadataUpdatedEvent.OutputObject
    >;
    ProviderMetadataUpdated: TypedContractEvent<
      ProviderMetadataUpdatedEvent.InputTuple,
      ProviderMetadataUpdatedEvent.OutputTuple,
      ProviderMetadataUpdatedEvent.OutputObject
    >;

    "ProviderRegistered(address,string)": TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;
    ProviderRegistered: TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;

    "ProviderStatusChanged(address,bool)": TypedContractEvent<
      ProviderStatusChangedEvent.InputTuple,
      ProviderStatusChangedEvent.OutputTuple,
      ProviderStatusChangedEvent.OutputObject
    >;
    ProviderStatusChanged: TypedContractEvent<
      ProviderStatusChangedEvent.InputTuple,
      ProviderStatusChangedEvent.OutputTuple,
      ProviderStatusChangedEvent.OutputObject
    >;
  };
}
