/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EKYCConsentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "consents"
      | "getConsentDetails"
      | "getUserConsents"
      | "grantConsent"
      | "isConsentValid"
      | "revokeConsent"
      | "userConsents"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ConsentGranted" | "ConsentRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "consents", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getConsentDetails",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserConsents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantConsent",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isConsentValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeConsent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userConsents",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "consents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getConsentDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserConsents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConsentValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userConsents",
    data: BytesLike
  ): Result;
}

export namespace ConsentGrantedEvent {
  export type InputTuple = [
    consentId: BytesLike,
    user: AddressLike,
    requester: AddressLike
  ];
  export type OutputTuple = [
    consentId: string,
    user: string,
    requester: string
  ];
  export interface OutputObject {
    consentId: string;
    user: string;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentRevokedEvent {
  export type InputTuple = [consentId: BytesLike, user: AddressLike];
  export type OutputTuple = [consentId: string, user: string];
  export interface OutputObject {
    consentId: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EKYCConsent extends BaseContract {
  connect(runner?: ContractRunner | null): EKYCConsent;
  waitForDeployment(): Promise<this>;

  interface: EKYCConsentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  consents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        requester: string;
        user: string;
        dataHash: string;
        expiryTimestamp: bigint;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  getConsentDetails: TypedContractMethod<
    [consentId: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        requester: string;
        user: string;
        dataHash: string;
        expiryTimestamp: bigint;
        isRevoked: boolean;
      }
    ],
    "view"
  >;

  getUserConsents: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  grantConsent: TypedContractMethod<
    [requester: AddressLike, dataHash: BytesLike, validityPeriod: BigNumberish],
    [string],
    "nonpayable"
  >;

  isConsentValid: TypedContractMethod<
    [consentId: BytesLike],
    [boolean],
    "view"
  >;

  revokeConsent: TypedContractMethod<
    [consentId: BytesLike],
    [void],
    "nonpayable"
  >;

  userConsents: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "consents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        requester: string;
        user: string;
        dataHash: string;
        expiryTimestamp: bigint;
        isRevoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConsentDetails"
  ): TypedContractMethod<
    [consentId: BytesLike],
    [
      [string, string, string, bigint, boolean] & {
        requester: string;
        user: string;
        dataHash: string;
        expiryTimestamp: bigint;
        isRevoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserConsents"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantConsent"
  ): TypedContractMethod<
    [requester: AddressLike, dataHash: BytesLike, validityPeriod: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isConsentValid"
  ): TypedContractMethod<[consentId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revokeConsent"
  ): TypedContractMethod<[consentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userConsents"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "ConsentGranted"
  ): TypedContractEvent<
    ConsentGrantedEvent.InputTuple,
    ConsentGrantedEvent.OutputTuple,
    ConsentGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentRevoked"
  ): TypedContractEvent<
    ConsentRevokedEvent.InputTuple,
    ConsentRevokedEvent.OutputTuple,
    ConsentRevokedEvent.OutputObject
  >;

  filters: {
    "ConsentGranted(bytes32,address,address)": TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;
    ConsentGranted: TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;

    "ConsentRevoked(bytes32,address)": TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
    ConsentRevoked: TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
  };
}
