/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EKYC__factory } from "./EKYC__factory";
export { EKYCConsent__factory } from "./EKYCConsent__factory";
export { EKYCRegistry__factory } from "./EKYCRegistry__factory";
